acme_api:
    resource: "@AcmeApiBundle/Controller/"
    type:     annotation
#    prefix:   /acme

acme_api_demos:
    type: rest
    resource: Acme\ApiBundle\Controller\DemoController

app:
    resource: "@AppBundle/Controller/"
    type: annotation

products:
    type: annotation
    prefix: /products
    resource: AppBundle\Controller\ProductApiController





#
#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
#    prefix: "/api/doc"
#
#api:
#    type: rest
#    resource: "routing_api.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"