app:
    resource: '@AppBundle/Controller/'
    type: annotation


#
#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
#    prefix: "/api/doc"
#
#api:
#    type: rest
#    resource: "routing_api.yml"
products:
    type: rest
    resource: AppBundle\Controller\ProductApiController